language: java
addons:
  sonarcloud:
    organization: "royshahaf-github"
    token:
      secure: "Z0JgmVAMNrLhV0NbWzJM07SQ9Fay2++6tsPMxeVWDh3ZlGVOJVCdocRt8UnKhwCQTzDebqO9Rt9oZsvX94+T/eGqCfqsFADk07FJWIDoK1ViyIr04Xzp7vOQYLPYFiWdjDq5H8tXSe+zuTnc1+edQs+Edhziy2Y83C/paW/dQhs1rftFKBYyLB9NnuB0panz7bzZq9mjMA3JLGfwqtCEHxGLqRzU6+T4u8CRQ6Y+6Icxy9SDuv7xAFE5CuKDOwFR/nL0aJ0NUb+K/h6EtuCXTc8sWQG1lS8V9TO/Q2xOSjXd6Lc+V3tzeSWIVU5u8glMMggKM917YIhvSdXLD3/Jjk/eZxWjOd7zHsv+U/4GPgBeGhXyOIB2CkfDDkE+r7qiJWe8UNSBO8X1iXlweWiP+u7lgBcIjGPFFZn3981X40BriJJUJyFSIo2N0sT/1S24rdJHuHutBGYIbIhodtaTmShE7DgwiVoZjxZCo8DP/V2k+Nf5oEkILIh1CAOBJajUwACrEkwdtuJwB1jmxLd78nuTdV+AWYPGajnJCQxWAP4wZQsHzy20GT2TtKMxbtC4qe9LcP94bDcHm/RnKXAAuUNSYnz8LVLeJkQOlaiMHqWha4pC/m5TV9NVC+eqNI8VJ7KQD21kJnyQ0h/9e1rea+8Qd676PK2JaQO3EVWU5LY=" # encrypted value of your token
script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar